server:
  port: 8080
spring:
  logging:
    level:
      org:
        hibernate:
          SQL: DEBUG
          type:
            descriptor:
              sql:
                BasicBinder: TRACE
        springframework:
          security=DEBUG:
  profiles:
    active: dev
  datasource:
    url: jdbc:postgresql://${DB_URL}?createDatabaseIfNotExist=true
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
jwt:
  secret: ${JWT_KEY}
  expiration: 4320000